refine pool create delete
F5Networks/f5-openstack-agent pull request #1483
Opened 2020-10-18 01:07 UTC by jikui

@<reviewer_id>
#### What issues does this address?
Fixes #<issueid>
WIP #<issueid>
...

#### What's this change do?

#### Where should the reviewer start?

#### Any background context?

2020-10-18 16:00 UTC, zhaoqin-github requested changes

2020-10-18 16:00 UTC, zhaoqin-github commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +            mgr._search_element(listener, service)
you may not need to search it again.

2020-10-18 16:00 UTC, zhaoqin-github commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +                mgr._search_element(listener, service)
you may not need to search it again.

2020-10-18 23:50 UTC, jikui commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +            mgr._search_element(listener, service)
qin, if we call the pool's creation and deletion without listener's creation/deletion/update, then the listener's _search_element will not be used. Hence the service's listener key will not be set properly.
That's my thought about why I explicitly called _search_element for the listener here.

Let's talk in detail soon.

2020-10-18 23:51 UTC, jikui commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +                mgr._search_element(listener, service)
The same as above

2020-10-19 02:21 UTC, jikui commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +            mgr._search_element(listener, service)
Qin is right.  Corrected it.

2020-10-19 02:47 UTC, zhaoqin-github approved these changes

2020-10-19 02:47 UTC, merged