member create/deletion/update
F5Networks/f5-openstack-agent pull request #1484
Opened 2020-10-19 10:06 UTC by jikui

@<reviewer_id>
#### What issues does this address?
Fixes #<issueid>
WIP #<issueid>
...

#### What's this change do?

#### Where should the reviewer start?

#### Any background context?

2020-10-20 16:34 UTC, zhaoqin-github requested changes

2020-10-20 16:34 UTC, zhaoqin-github commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +        self.driver = driver
remove this ?

2020-10-20 16:34 UTC, zhaoqin-github commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +                LOG.error("Unexpected node deletion error: %s",
raise exception or not?

2020-10-21 01:48 UTC, jikui commented on f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
> +                LOG.error("Unexpected node deletion error: %s",
Let's discuss this further in details.

2020-10-21 02:21 UTC, zhaoqin-github approved these changes

2020-10-21 02:22 UTC, merged