release 9.9.3
F5Networks/f5-openstack-agent pull request #1701
Opened 2021-05-08 09:17 UTC by Niklaus-xie

mainly include some bug fixes and member status update
modifications.

2021-05-08 10:02 UTC, zhaoqin-github approved these changes

2021-05-08 13:13 UTC, olvandeng requested changes
Looks like the release is the patch release, could we use v9.9.2 version, or refresh v9.9.2 release ?

2021-05-10 02:40 UTC, Niklaus-xie commented
> refresh v9.9.2 release

refresh v9.9.2 release

> Looks like the release is the patch release, could we use v9.9.2 version, or refresh v9.9.2 release ?

  refresh v9.9.2 release 的意思是？ 是说 把 目前 已经 release的 v9.9.2直接 删掉么  重新弄一个  v9.9.2 的 新的么？

2021-05-10 03:38 UTC, olvandeng approved these changes
After discussion, it is better to use build number 9.9.3.

2021-05-10 03:54 UTC, merged